/*
 * Copyright 2021, Intel Corporation
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License,
 * version 2 as published by the Free Software Foundation..
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: librpma_aof_update.proto */

#ifndef PROTOBUF_C_librpma_5faof_5fupdate_2eproto__INCLUDED
#define PROTOBUF_C_librpma_5faof_5fupdate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AOFUpdateRequest AOFUpdateRequest;
typedef struct _AOFUpdateResponse AOFUpdateResponse;


/* --- enums --- */


/* --- messages --- */

struct  _AOFUpdateRequest
{
  ProtobufCMessage base;
  /*
   * an offset of the 1st region to be flushed within its memory registration 
   */
  uint64_t append_offset;
  /*
   * a length of the 1st region to be flushed 
   */
  uint64_t append_length;
  /*
   * an offset of the atomic write and also of the 2nd region to be flushed
   * within its memory registration
   */
  uint64_t pointer_offset;
  /*
   * a user-defined operation context 
   */
  uint64_t op_context;
};
#define AOF_UPDATE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aof_update_request__descriptor) \
    , 0, 0, 0, 0 }


struct  _AOFUpdateResponse
{
  ProtobufCMessage base;
  /*
   * a user-defined context of the AOF update operation's request 
   */
  uint64_t op_context;
};
#define AOF_UPDATE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aof_update_response__descriptor) \
    , 0 }


/* AOFUpdateRequest methods */
void   aof_update_request__init
                     (AOFUpdateRequest         *message);
size_t aof_update_request__get_packed_size
                     (const AOFUpdateRequest   *message);
size_t aof_update_request__pack
                     (const AOFUpdateRequest   *message,
                      uint8_t             *out);
size_t aof_update_request__pack_to_buffer
                     (const AOFUpdateRequest   *message,
                      ProtobufCBuffer     *buffer);
AOFUpdateRequest *
       aof_update_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aof_update_request__free_unpacked
                     (AOFUpdateRequest *message,
                      ProtobufCAllocator *allocator);
/* AOFUpdateResponse methods */
void   aof_update_response__init
                     (AOFUpdateResponse         *message);
size_t aof_update_response__get_packed_size
                     (const AOFUpdateResponse   *message);
size_t aof_update_response__pack
                     (const AOFUpdateResponse   *message,
                      uint8_t             *out);
size_t aof_update_response__pack_to_buffer
                     (const AOFUpdateResponse   *message,
                      ProtobufCBuffer     *buffer);
AOFUpdateResponse *
       aof_update_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aof_update_response__free_unpacked
                     (AOFUpdateResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AOFUpdateRequest_Closure)
                 (const AOFUpdateRequest *message,
                  void *closure_data);
typedef void (*AOFUpdateResponse_Closure)
                 (const AOFUpdateResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor aof_update_request__descriptor;
extern const ProtobufCMessageDescriptor aof_update_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_librpma_5faof_5fupdate_2eproto__INCLUDED */
